# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Find
find_keyword = { fg = "#FD4663", bold = true, italic = true, underline = true }
find_position = { fg = "#FD4663", bold = true, italic = true }

# Marker
marker_copied = { fg = "#00994f", bg = "#00994f" }
marker_cut = { fg = "#00994f", bg = "#00994f" }
marker_marked = { fg = "#FD4663", bg = "#FD4663" }
marker_selected = { fg = "#9BFECE", bg = "#9BFECE" }

# Count
count_copied = { fg = "#e6e1e5", bg = "#00994f" }
count_cut = { fg = "#e6e1e5", bg = "#00994f" }
count_selected = { fg = "#000000", bg = "#9BFECE" }

# Border
border_style  = { fg = "#fff59b" }

# : ]]]


# : Status [[[

[status]
overall = { fg = "#fff59b" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#fff59b", bg = "#070722" }
progress_error = { fg = "#FD4663", bg = "#070722" }

# Permissions
perm_type = { fg = "#a9aefe" }
perm_write = { fg = "#9BFECE" }
perm_exec = { fg = "#FD4663" }
perm_read = { fg = "#00994f" }
perm_sep = { fg = "#998a00" }

# : ]]]


# : Mode [[[

[mode]

normal_main = { bg = "#fff59b", fg = "#000000", bold = true }
normal_alt  = { bg = "#0b0b37", fg = "#ffffff" }

select_main = { bg = "#a9aefe", fg = "#e6e1e5", bold = true }
select_alt  = { bg = "#0b0b37", fg = "#ffffff" }

unset_main = { bg = "#9BFECE", fg = "#000000", bold = true }
unset_alt  = { bg = "#0b0b37", fg = "#ffffff" }

# : ]]]


# : Input [[[

[input]
border = { fg = "#fff59b" }
title = {}
value = { fg = "#ffffff" }
selected = { reversed = true }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#fff59b", bold = true, bg = "#070722" }
inactive = { fg = "#a9aefe", bg = "#070722" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#fff59b", bg = "#000000" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#fff59b" }
title = {}
hovered = { fg = "#00994f", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#070722" }
cand = { fg = "#fff59b" }
rest = { fg = "#000000" }
desc = { fg = "#ffffff" }
separator = " ▶ "
separator_style = { fg = "#ffffff" }

# : ]]]

# : Spotter [[[

[spot]
border   = { fg = "#fff59b" }
title    = { fg = "#fff59b" }
tbl_col  = { fg = "#ffffff" }
tbl_cell = { fg = "#ffffff", bg = "#070722" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#e6e1e5", bg = "#a9aefe" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#9BFECE" }
title_warn = { fg = "#fff59b" }
title_error = { fg = "#FD4663" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { mime = "*", is = "orphan", fg = "#ffffff", bg = "#990018" },
    { mime = "application/*exec*", fg = "#FD4663" },

    # Fallback
    { url = "*", fg = "#ffffff" },
    { url = "*/", fg = "#fff59b" },
]

# : ]]]
